# Normalizing JSON

<img src="../extra/json_to_df.png"  width="150" height="150">

In [2]:
import pandas as pd
import json
f = open('sea_level_rise.json','r')
data = json.load(f)

# default arguments

In [3]:
df = pd.json_normalize(data)
df

,data,meta.view.id,meta.view.name,meta.view.assetType,meta.view.attribution,meta.view.attributionLink,meta.view.averageRating,meta.view.category,meta.view.createdAt,meta.view.description,...,meta.view.owner.type,meta.view.owner.flags,meta.view.rights,meta.view.tableAuthor.id,meta.view.tableAuthor.displayName,meta.view.tableAuthor.screenName,meta.view.tableAuthor.type,meta.view.tableAuthor.flags,meta.view.tags,meta.view.flags
0,"[[row-q28d.27v6-9f5h, 00000000-0000-0000-C94D-...",esku-ejgv,"100-Year Storm + 24"" Sea Level Rise",dataset,BCDC,https://explorer.adaptingtorisingtides.org/home,0,Public Safety,1582651989,This data originates from San Francisco Bay Co...,...,interactive,[acceptedEula],[read],rtw4-hi68,Alex Morrison,Alex Morrison,interactive,[acceptedEula],[hcr],"[default, ownerMayBeContacted, restorable, res..."

# record_path argument

In [ ]:
df = pd.json_normalize(data,record_path='data')
df

In [4]:
df = pd.json_normalize(data,record_path=['meta','view','columns'])
df

,id,name,dataTypeName,fieldName,position,renderTypeName,flags,description,tableColumnId,cachedContents.non_null,cachedContents.largest,cachedContents.null,cachedContents.top,cachedContents.smallest,cachedContents.cardinality
0,-1,sid,meta_data,:sid,0,meta_data,[hidden],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-1,id,meta_data,:id,0,meta_data,[hidden],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-1,position,meta_data,:position,0,meta_data,[hidden],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-1,created_at,meta_data,:created_at,0,meta_data,[hidden],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-1,created_meta,meta_data,:created_meta,0,meta_data,[hidden],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,-1,updated_at,meta_data,:updated_at,0,meta_data,[hidden],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,-1,updated_meta,meta_data,:updated_meta,0,meta_data,[hidden],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,-1,meta,meta_data,:meta,0,meta_data,[hidden],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,453003560,the_geom,multipolygon,the_geom,1,multipolygon,NaN,Location Geometry,95163781.0,NaN,NaN,NaN,NaN,NaN,NaN
9,453003561,gridcode,number,gridcode,2,number,NaN,Gridcode from original raster (N/A),95163782.0,7,7,0,"[{'item': '1', 'count': '1'}, {'item': '4', 'c...",1,7
10,453003565,DEPTH_FT,text,depth_ft,3,text,NaN,Depth of original raster (N/A),95163783.0,0,NaN,7,NaN,NaN,0
11,453003585,Shape_Leng,number,shape_leng,4,number,NaN,Planar lengths of the polygon,95163784.0,7,403497.407074,0,"[{'item': '14324.6565348', 'count': '1'}, {'it...",1956.61676588,7
12,453003586,Shape_Area,number,shape_area,5,number,NaN,Planar area of the polygon,95163785.0,7,5109724.35419,0,"[{'item': '65613.6489693', 'count': '1'}, {'it...",6220.48975269,7

# meta argument

In [5]:
df = pd.json_normalize(data,record_path='data',meta='meta')
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,meta
0,row-q28d.27v6-9f5h,00000000-0000-0000-C94D-CEF7ABC1DF4E,0,1582656196,None,1582656196,None,{ },MULTIPOLYGON (((-122.39340451043492 37.7082709...,1,None,403497.407074,5109724.35419,"{'view': {'id': 'esku-ejgv', 'name': '100-Year..."
1,row-cghi-7qw3_w8q7,00000000-0000-0000-7EAE-0CC6453E9A04,0,1582656196,None,1582656196,None,{ },MULTIPOLYGON (((-122.3933817480972 37.70827985...,2,None,219147.103346,794145.707602,"{'view': {'id': 'esku-ejgv', 'name': '100-Year..."
2,row-2mj3-iidx.ww5b,00000000-0000-0000-B701-B26A64CD77D6,0,1582656196,None,1582656196,None,{ },MULTIPOLYGON (((-122.39236645792793 37.6997140...,3,None,103724.875386,206087.884076,"{'view': {'id': 'esku-ejgv', 'name': '100-Year..."
3,row-sxi6.ix49_8z8p,00000000-0000-0000-72A3-7649F9FF2FDE,0,1582656196,None,1582656196,None,{ },MULTIPOLYGON (((-122.38167178195368 37.7115856...,4,None,14324.6565348,65613.6489693,"{'view': {'id': 'esku-ejgv', 'name': '100-Year..."
4,row-ybre~jfpf~e8pe,00000000-0000-0000-E142-2963FA37BC47,0,1582656196,None,1582656196,None,{ },MULTIPOLYGON (((-122.36361154704703 37.7190288...,5,None,6305.14575212,6559.42001802,"{'view': {'id': 'esku-ejgv', 'name': '100-Year..."
5,row-xazf-59va_ih27,00000000-0000-0000-1A01-86FD3A7CADD9,0,1582656196,None,1582656196,None,{ },MULTIPOLYGON (((-122.36358900923197 37.7190107...,6,None,3775.37755422,6220.48975269,"{'view': {'id': 'esku-ejgv', 'name': '100-Year..."
6,row-fqce_m6u8_p6iy,00000000-0000-0000-9D29-72572931FE29,0,1582656196,None,1582656196,None,{ },MULTIPOLYGON (((-122.36506748482017 37.7252558...,7,None,1956.61676588,9708.36506382,"{'view': {'id': 'esku-ejgv', 'name': '100-Year..."

# max_level argument

In [6]:
df = pd.json_normalize(data, record_path=['meta','view','approvals'], max_level=0)
df

,reviewedAt,reviewedAutomatically,state,submissionId,submissionObject,submissionOutcome,submittedAt,workflowId,reviewer,submissionDetails,submissionOutcomeApplication,submitter
0,1592441916,False,approved,2162099,public_audience_request,change_audience,1588716520,2017,"{'id': 's7k8-df3k', 'displayName': 'Jason Lally'}",{'permissionType': 'read'},"{'endedAt': 1592441916, 'failureCount': 0, 'st...","{'id': 'rtw4-hi68', 'displayName': 'Alex Morri..."

In [7]:
df = pd.json_normalize(data, record_path=['meta','view','approvals'], max_level=1)
df

,reviewedAt,reviewedAutomatically,state,submissionId,submissionObject,submissionOutcome,submittedAt,workflowId,reviewer.id,reviewer.displayName,submissionDetails.permissionType,submissionOutcomeApplication.endedAt,submissionOutcomeApplication.failureCount,submissionOutcomeApplication.startedAt,submissionOutcomeApplication.status,submitter.id,submitter.displayName
0,1592441916,False,approved,2162099,public_audience_request,change_audience,1588716520,2017,s7k8-df3k,Jason Lally,read,1592441916,0,1592441916,success,rtw4-hi68,Alex Morrison